# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FarboxWeb', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file_hash', models.CharField(max_length=200)),
                ('file_size', models.BigIntegerField()),
            ],
        ),
    ]
