# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FarboxWeb', '0003_realfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualFile',
            fields=[
                ('path_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField()),
                ('path_name', models.CharField(max_length=200)),
                ('is_file', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='realfile',
            name='file_hash',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='virtualfile',
            name='realfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarboxWeb.RealFile'),
        ),
    ]
