# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarboxWeb', '0004_auto_20160524_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualfile',
            name='realfile',
        ),
        migrations.AddField(
            model_name='virtualfile',
            name='realfilename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='virtualfile',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
