# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 08:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FarboxWeb', '0006_auto_20160524_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualfile',
            name='file_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualfile',
            name='upload_time',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 6, 5, 8, 38, 47, 568143, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
