# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarboxWeb', '0009_auto_20160605_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualfile',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
    ]
